# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DogrulamaEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1084, 520)
        Form.setStyleSheet("#Form{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.0113636, stop:0 rgba(38, 77, 135, 255), stop:0.778409 rgba(198, 237, 252, 255));\n"
"\n"
"}")
        self.lineEdit_VCode = QtWidgets.QLineEdit(Form)
        self.lineEdit_VCode.setGeometry(QtCore.QRect(410, 240, 211, 31))
        self.lineEdit_VCode.setObjectName("lineEdit_VCode")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(410, 210, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_Timer = QtWidgets.QLineEdit(Form)
        self.lineEdit_Timer.setGeometry(QtCore.QRect(410, 280, 51, 20))
        self.lineEdit_Timer.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 75 9pt \"MS Shell Dlg 2\";\n"
"")
        self.lineEdit_Timer.setReadOnly(True)
        self.lineEdit_Timer.setObjectName("lineEdit_Timer")
        self.pushButton_SendAgain = QtWidgets.QPushButton(Form)
        self.pushButton_SendAgain.setGeometry(QtCore.QRect(550, 280, 75, 23))
        self.pushButton_SendAgain.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 63 9pt \"Segoe UI Semibold\";")
        self.pushButton_SendAgain.setObjectName("pushButton_SendAgain")
        self.pushButton_Verify = QtWidgets.QPushButton(Form)
        self.pushButton_Verify.setGeometry(QtCore.QRect(550, 310, 75, 23))
        self.pushButton_Verify.setStyleSheet("background-color: rgb(5, 155, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";")
        self.pushButton_Verify.setObjectName("pushButton_Verify")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Verification Code"))
        self.lineEdit_Timer.setText(_translate("Form", "00:00"))
        self.pushButton_SendAgain.setText(_translate("Form", "Send Again"))
        self.pushButton_Verify.setText(_translate("Form", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
