# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainSC.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(1086, 520)
        MainScreen.setStyleSheet("#MainScreen{\n"
"background-image: url(:/MainBackground/DigitalBackground.jpg);\n"
"}")
        self.frame = QtWidgets.QFrame(MainScreen)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1091, 521))
        self.frame.setStyleSheet("#frame{\n"
"border-image: url(:/MainBackground/DigitalBackground.jpg);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_EncryptionS = QtWidgets.QPushButton(self.frame)
        self.pushButton_EncryptionS.setGeometry(QtCore.QRect(410, 110, 231, 51))
        self.pushButton_EncryptionS.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: qlineargradient(spread:pad, x1:0.955, y1:0.943182, x2:0.011, y2:0.977273, stop:0 rgba(0, 120, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.pushButton_EncryptionS.setObjectName("pushButton_EncryptionS")
        self.pushButton_2_DecryptionS = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_DecryptionS.setGeometry(QtCore.QRect(410, 180, 231, 51))
        self.pushButton_2_DecryptionS.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.028, x2:1, y2:0, stop:0 rgba(16, 122, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.pushButton_2_DecryptionS.setObjectName("pushButton_2_DecryptionS")
        self.pushButton_2_ImageDEC = QtWidgets.QPushButton(self.frame)
        self.pushButton_2_ImageDEC.setGeometry(QtCore.QRect(410, 320, 231, 51))
        self.pushButton_2_ImageDEC.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.028, x2:1, y2:0, stop:0 rgba(16, 122, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.pushButton_2_ImageDEC.setObjectName("pushButton_2_ImageDEC")
        self.pushButton_ImageENC = QtWidgets.QPushButton(self.frame)
        self.pushButton_ImageENC.setGeometry(QtCore.QRect(410, 250, 231, 51))
        self.pushButton_ImageENC.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: qlineargradient(spread:pad, x1:0.955, y1:0.943182, x2:0.011, y2:0.977273, stop:0 rgba(0, 120, 200, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 14pt \"Segoe UI Black\";")
        self.pushButton_ImageENC.setObjectName("pushButton_ImageENC")

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "Form"))
        self.pushButton_EncryptionS.setText(_translate("MainScreen", "TEXT ENCRYPTION"))
        self.pushButton_2_DecryptionS.setText(_translate("MainScreen", "TEXT DECRYPTION"))
        self.pushButton_2_ImageDEC.setText(_translate("MainScreen", "IMAGE DECRYPTION"))
        self.pushButton_ImageENC.setText(_translate("MainScreen", "IMAGE ENCRYPTION"))
import Resimler_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainScreen = QtWidgets.QWidget()
    ui = Ui_MainScreen()
    ui.setupUi(MainScreen)
    MainScreen.show()
    sys.exit(app.exec_())
